import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import * as React from "react";
import "./globals.css";

import { Providers } from "./providers";
import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "bg-background min-h-screen font-sans antialiased",
          fontSans.variable
        )}
      >
        <Providers>
          <main className="mx-auto min-h-screen max-w-xl px-6 py-12">
            {children}
          </main>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
